export const ADD_ANNOTATION = 'ADD_ANNOTATION';
export const INITIAL_TEAMS_DATA = 'INITIAL_TEAMS_DATA';
//modal
export const SHOW_GAME_SET_MODAL = 'SHOW_GAME_SET_MODAL';
export const CLOSE_GAME_SET_MODAL = 'CLOSE_GAME_SET_MODAL';
